version: "3"

services:
  postgres_keycloak:
    image: postgres:9.2-alpine
    container_name: demo_postgres_keycloak
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo

  keycloak:
    image: jboss/keycloak-postgres:3.0.0.Final
    container_name: demo_keycloak
    restart: unless-stopped
    ports:
      - 5050:8080
    environment:
      - KEYCLOAK_USER=demo
      - KEYCLOAK_PASSWORD=demo
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - POSTGRES_DATABASE=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    links:
      - postgres_keycloak:postgres
    # volumes:
    #   - ./keycloak/data:/data
    # command: "-Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/data/keycloak.json -Dkeycloak.migration.realmName=demo"

networks:
  default:
    external:
      name: demo
